# Generated by Django 2.2.16 on 2021-12-12 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211212_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
